%!  INPUT (Set<Node> nodes, Set<Edge> edges) {
%!      node(n.label) for n in nodes;
%!      edge(e.first.label, e.second.label) for e in edges;
%!  }

%!  OUTPUT {
%!      colored_nodes = set { color/2 -> ColoredNode };
%!      labels_by_color = dictionary {
%!          query: color(_,C);
%!          key: C;
%!          content: set { query: color(X,C); content: X; };
%!      };
%!  }

color(X, red) v color(X, green) v color(X, blue) :- node(X).

:- edge(X, Y), color(X, C), color(Y, C).
